---
framework: jest
postMerge:
  pattern:
    - "./packages/**/test/**/*.test.{ts,tsx}"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./packages/**/test/**/*.test.{ts,tsx}"
preRun:
  - yarn install
  - yarn build
postRun:
  - node --version
version: 2.0

